spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

  datasource:
    # url: jdbc:h2:mem:localdb
    url: jdbc:h2:tcp://localhost/~/local
    username: sa
    password:
    driver-class-name: org.h2.Driver